[package]
name = "malwaredb-virustotal-bin"
description = "VirusTotal command line client"
keywords = ["cybersecurity", "malware", "malware-analysis", "virustotal"]
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
clap = { workspace = true, features = ["derive", "env", "help", "std", "usage"], default-features = false }
hex = { workspace = true, features = ["alloc"], default-features = false }
serde_json = { workspace = true, features = ["alloc"], default-features = false }
sha2 = { workspace = true, default-features = false }
malwaredb-virustotal = { workspace = true, features = ["chrono", "clap", "tokio"], default-features = false }
tokio = { workspace = true, features = ["rt", "macros"], default-features = false }

[target.'cfg(target_env = "musl")'.dependencies]
malwaredb-virustotal = { workspace = true, features = ["chrono", "clap", "native-tls-vendored", "tokio"], default-features = false }
