[package]
name = "malwaredb-virustotal-bin"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Richard Zak <richard.j.zak@gmail.com>"]
description = "VirusTotal command line client"
homepage = "https://malwaredb.net/"
repository = "https://github.com/malwaredb/vt-client"
keywords = ["cybersecurity", "malware", "malware-analysis", "virustotal"]

[dependencies]
anyhow = { version = "1.0", features = ["std"] }
clap = { version = "4.5", features = ["derive", "env", "help", "std", "usage"], default-features = false }
hex = { version = "0.4.3", features = ["alloc"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["alloc"], default-features = false }
sha2 = { version = "0.10.8", default-features = false }
malwaredb-virustotal = { path = "..", version = "0", features = ["clap"], default-features = false }
tokio = { version = "1.39", features = ["rt", "macros"], default-features = false }
