name: Commisery
on:
  workflow_call:
  pull_request:
    types: [edited, opened, synchronize, reopened]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# This workflow uses a third-party action.
# The existence of a `permissions` key denies all
# permissions except those explicitly specified.
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443

      - name: Run Commisery
        uses: tomtom-international/commisery-action@1910dece6192da25e159477b7de11ec1b722eefc # v8.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          validate-pull-request: false
          validate-pull-request-title-bump: false
